-- Начальные данные для таблиц Supabase

-- Вставка валют (fiat)
INSERT INTO currencies (code, name, symbol, flag, type) VALUES
('USD', 'Доллар США', '$', '🇺🇸', 'fiat'),
('EUR', 'Евро', '€', '🇪🇺', 'fiat'),
('RUB', 'Российский рубль', '₽', '🇷🇺', 'fiat'),
('GBP', 'Фунт стерлингов', '£', '🇬🇧', 'fiat'),
('JPY', 'Японская иена', '¥', '🇯🇵', 'fiat'),
('CNY', 'Китайский юань', '¥', '🇨🇳', 'fiat'),
('CHF', 'Швейцарский франк', 'CHF', '🇨🇭', 'fiat'),
('CAD', 'Канадский доллар', 'C$', '🇨🇦', 'fiat'),
('AUD', 'Австралийский доллар', 'A$', '🇦🇺', 'fiat'),
('KZT', 'Казахстанский тенге', '₸', '🇰🇿', 'fiat'),
('AZN', 'Азербайджанский манат', '₼', '🇦🇿', 'fiat'),
('AMD', 'Армянский драм', '֏', '🇦🇲', 'fiat'),
('BYN', 'Белорусский рубль', 'Br', '🇧🇾', 'fiat'),
('BRL', 'Бразильский реал', 'R$', '🇧🇷', 'fiat'),
('HUF', 'Венгерский форинт', 'Ft', '🇭🇺', 'fiat'),
('HKD', 'Гонконгский доллар', 'HK$', '🇭🇰', 'fiat'),
('GEL', 'Грузинский лари', '₾', '🇬🇪', 'fiat'),
('DKK', 'Датская крона', 'kr', '🇩🇰', 'fiat'),
('AED', 'Дирхам ОАЭ', 'د.إ', '🇦🇪', 'fiat'),
('INR', 'Индийская рупия', '₹', '🇮🇳', 'fiat'),
('KRW', 'Южнокорейская вона', '₩', '🇰🇷', 'fiat'),
('MXN', 'Мексиканское песо', '$', '🇲🇽', 'fiat'),
('NOK', 'Норвежская крона', 'kr', '🇳🇴', 'fiat'),
('NZD', 'Новозеландский доллар', 'NZ$', '🇳🇿', 'fiat'),
('PLN', 'Польский злотый', 'zł', '🇵🇱', 'fiat'),
('SEK', 'Шведская крона', 'kr', '🇸🇪', 'fiat'),
('SGD', 'Сингапурский доллар', 'S$', '🇸🇬', 'fiat'),
('THB', 'Тайский бат', '฿', '🇹🇭', 'fiat'),
('TRY', 'Турецкая лира', '₺', '🇹🇷', 'fiat'),
('UAH', 'Украинская гривна', '₴', '🇺🇦', 'fiat'),
('UZS', 'Узбекский сум', 'so''m', '🇺🇿', 'fiat'),
('ZAR', 'Южноафриканский рэнд', 'R', '🇿🇦', 'fiat'),
('ARS', 'Аргентинское песо', '$', '🇦🇷', 'fiat'),
('EGP', 'Египетский фунт', '£', '🇪🇬', 'fiat'),
('ILS', 'Израильский шекель', '₪', '🇮🇱', 'fiat'),
('IDR', 'Индонезийская рупия', 'Rp', '🇮🇩', 'fiat'),
('ISK', 'Исландская крона', 'kr', '🇮🇸', 'fiat'),
('COP', 'Колумбийское песо', '$', '🇨🇴', 'fiat'),
('KWD', 'Кувейтский динар', 'د.ك', '🇰🇼', 'fiat'),
('MYR', 'Малайзийский ринггит', 'RM', '🇲🇾', 'fiat'),
('MAD', 'Марокканский дирхам', 'د.م.', '🇲🇦', 'fiat'),
('NGN', 'Нигерийская найра', '₦', '🇳🇬', 'fiat'),
('PKR', 'Пакистанская рупия', '₨', '🇵🇰', 'fiat'),
('PEN', 'Перуанский соль', 'S/', '🇵🇪', 'fiat'),
('RON', 'Румынский лей', 'lei', '🇷🇴', 'fiat'),
('SAR', 'Саудовский риял', '﷼', '🇸🇦', 'fiat'),
('PHP', 'Филиппинское песо', '₱', '🇵🇭', 'fiat'),
('CZK', 'Чешская крона', 'Kč', '🇨🇿', 'fiat'),
('CLP', 'Чилийское песо', '$', '🇨🇱', 'fiat'),
('LKR', 'Шри-Ланкийская рупия', 'Rs', '🇱🇰', 'fiat'),
('VND', 'Вьетнамский донг', '₫', '🇻🇳', 'fiat');

-- Вставка криптовалют
INSERT INTO currencies (code, name, symbol, flag, type) VALUES
('BTC', 'Bitcoin', '₿', '₿', 'crypto'),
('ETH', 'Ethereum', 'Ξ', 'Ξ', 'crypto'),
('USDT', 'Tether', '₮', '₮', 'crypto'),
('BNB', 'Binance Coin', 'B', 'B', 'crypto'),
('SOL', 'Solana', 'S', 'S', 'crypto'),
('XRP', 'Ripple', 'X', 'X', 'crypto'),
('ADA', 'Cardano', 'A', 'A', 'crypto'),
('DOGE', 'Dogecoin', 'Ð', 'Ð', 'crypto'),
('TRX', 'Tron', 'T', 'T', 'crypto'),
('MATIC', 'Polygon', 'M', 'M', 'crypto'),
('DOT', 'Polkadot', 'D', 'D', 'crypto'),
('LTC', 'Litecoin', 'Ł', 'Ł', 'crypto'),
('SHIB', 'Shiba Inu', 'S', 'S', 'crypto'),
('AVAX', 'Avalanche', 'A', 'A', 'crypto'),
('UNI', 'Uniswap', 'U', 'U', 'crypto'),
('LINK', 'Chainlink', 'L', 'L', 'crypto'),
('XLM', 'Stellar', 'X', 'X', 'crypto'),
('ATOM', 'Cosmos', 'A', 'A', 'crypto'),
('XMR', 'Monero', 'M', 'M', 'crypto'),
('ETC', 'Ethereum Classic', 'E', 'E', 'crypto'),
('BCH', 'Bitcoin Cash', 'B', 'B', 'crypto'),
('NEAR', 'NEAR Protocol', 'N', 'N', 'crypto'),
('APT', 'Aptos', 'A', 'A', 'crypto'),
('FIL', 'Filecoin', 'F', 'F', 'crypto'),
('VET', 'VeChain', 'V', 'V', 'crypto'),
('ALGO', 'Algorand', 'A', 'A', 'crypto'),
('ICP', 'Internet Computer', 'I', 'I', 'crypto'),
('HBAR', 'Hedera', 'H', 'H', 'crypto'),
('QNT', 'Quant', 'Q', 'Q', 'crypto'),
('ARB', 'Arbitrum', 'A', 'A', 'crypto'),
('OP', 'Optimism', 'O', 'O', 'crypto'),
('IMX', 'Immutable X', 'I', 'I', 'crypto'),
('AAVE', 'Aave', 'A', 'A', 'crypto'),
('MKR', 'Maker', 'M', 'M', 'crypto'),
('GRT', 'The Graph', 'G', 'G', 'crypto'),
('SNX', 'Synthetix', 'S', 'S', 'crypto'),
('SAND', 'The Sandbox', 'S', 'S', 'crypto'),
('MANA', 'Decentraland', 'M', 'M', 'crypto'),
('AXS', 'Axie Infinity', 'A', 'A', 'crypto'),
('THETA', 'Theta Network', 'Θ', 'Θ', 'crypto'),
('FTM', 'Fantom', 'F', 'F', 'crypto'),
('EOS', 'EOS', 'E', 'E', 'crypto'),
('XTZ', 'Tezos', 'X', 'X', 'crypto'),
('FLOW', 'Flow', 'F', 'F', 'crypto'),
('EGLD', 'MultiversX', 'E', 'E', 'crypto');

-- Пример вставки начальных курсов (относительно KZT)
-- Эти значения нужно обновлять через API
INSERT INTO exchange_rates (from_currency, to_currency, rate, source) VALUES
('USD', 'KZT', 499.83, 'manual'),
('EUR', 'KZT', 581.5, 'manual'),
('RUB', 'KZT', 6.42, 'manual'),
('GBP', 'KZT', 595.20, 'manual'),
('BTC', 'USD', 72897.00, 'manual'),
('ETH', 'USD', 3245.00, 'manual'),
('USDT', 'USD', 1.00, 'manual');

-- Пример вставки акций
INSERT INTO stocks (symbol, name, price, change_amount, change_percent, is_up, market_cap, volume) VALUES
('AAPL', 'Apple Inc.', 150.25, 2.50, 1.69, true, 2500000000000, 50000000),
('GOOGL', 'Alphabet Inc.', 2800.50, -15.25, -0.54, false, 1800000000000, 2500000),
('MSFT', 'Microsoft Corporation', 305.75, 5.25, 1.75, true, 2300000000000, 30000000),
('TSLA', 'Tesla Inc.', 245.80, -8.20, -3.23, false, 780000000000, 45000000),
('AMZN', 'Amazon.com Inc.', 3200.00, 25.50, 0.80, true, 1600000000000, 3500000);