final Map<String, Map<String, dynamic>> worldCurrencies = {
  'USD': {'flag': '🇺🇸', 'name': 'Доллар США', 'price': '499,83 ₸', 'change': '+1,74 ₸', 'isUp': true},
  'EUR': {'flag': '🇪🇺', 'name': 'Евро', 'price': '581,5 ₸', 'change': '+4,16 ₸', 'isUp': true},
  'RUB': {'flag': '🇷🇺', 'name': 'Российский рубль', 'price': '6,42 ₸', 'change': '+0,01 ₸', 'isUp': true},
  'GBP': {'flag': '🇬🇧', 'name': 'Фунт стерлингов', 'price': '595,20 ₸', 'change': '-0,50 ₸', 'isUp': false},
  'JPY': {'flag': '🇯🇵', 'name': 'Японская иена', 'price': '3,20 ₸', 'change': '+0,05 ₸', 'isUp': true},
  'CNY': {'flag': '🇨🇳', 'name': 'Китайский юань', 'price': '64,80 ₸', 'change': '+0,30 ₸', 'isUp': true},
  'CHF': {'flag': '🇨🇭', 'name': 'Швейцарский франк', 'price': '532,10 ₸', 'change': '+1,20 ₸', 'isUp': true},
  'CAD': {'flag': '🇨🇦', 'name': 'Канадский доллар', 'price': '348,90 ₸', 'change': '+0,80 ₸', 'isUp': true},
  'AUD': {'flag': '🇦🇺', 'name': 'Австралийский доллар', 'price': '310,50 ₸', 'change': '+2,10 ₸', 'isUp': true},
  'KZT': {'flag': '🇰🇿', 'name': 'Казахстанский тенге', 'price': '1,00 ₸', 'change': '+0,00 ₸', 'isUp': true},
  'AZN': {'flag': '🇦🇿', 'name': 'Азербайджанский манат', 'price': '276,40 ₸', 'change': '+1,20 ₸', 'isUp': true},
  'AMD': {'flag': '🇦🇲', 'name': 'Армянский драм', 'price': '1,21 ₸', 'change': '+0,01 ₸', 'isUp': true},
  'BYN': {'flag': '🇧🇾', 'name': 'Белорусский рубль', 'price': '143,80 ₸', 'change': '+0,90 ₸', 'isUp': true},
  'BRL': {'flag': '🇧🇷', 'name': 'Бразильский реал', 'price': '94,20 ₸', 'change': '+0,50 ₸', 'isUp': true},
  'HUF': {'flag': '🇭🇺', 'name': 'Венгерский форинт', 'price': '1,32 ₸', 'change': '+0,02 ₸', 'isUp': true},
  'HKD': {'flag': '🇭🇰', 'name': 'Гонконгский доллар', 'price': '60,30 ₸', 'change': '+0,40 ₸', 'isUp': true},
  'GEL': {'flag': '🇬🇪', 'name': 'Грузинский лари', 'price': '172,50 ₸', 'change': '+1,10 ₸', 'isUp': true},
  'DKK': {'flag': '🇩🇰', 'name': 'Датская крона', 'price': '68,90 ₸', 'change': '+0,30 ₸', 'isUp': true},
  'AED': {'flag': '🇦🇪', 'name': 'Дирхам ОАЭ', 'price': '128,40 ₸', 'change': '+0,80 ₸', 'isUp': true},
  'INR': {'flag': '🇮🇳', 'name': 'Индийская рупия', 'price': '5,68 ₸', 'change': '+0,12 ₸', 'isUp': true},
  'KRW': {'flag': '🇰🇷', 'name': 'Южнокорейская вона', 'price': '0,37 ₸', 'change': '+0,01 ₸', 'isUp': true},
  'MXN': {'flag': '🇲🇽', 'name': 'Мексиканское песо', 'price': '27,50 ₸', 'change': '+0,20 ₸', 'isUp': true},
  'NOK': {'flag': '🇳🇴', 'name': 'Норвежская крона', 'price': '44,30 ₸', 'change': '+0,15 ₸', 'isUp': true},
  'NZD': {'flag': '🇳🇿', 'name': 'Новозеландский доллар', 'price': '289,70 ₸', 'change': '+1,30 ₸', 'isUp': true},
  'PLN': {'flag': '🇵🇱', 'name': 'Польский злотый', 'price': '118,60 ₸', 'change': '+0,70 ₸', 'isUp': true},
  'SEK': {'flag': '🇸🇪', 'name': 'Шведская крона', 'price': '45,20 ₸', 'change': '+0,25 ₸', 'isUp': true},
  'SGD': {'flag': '🇸🇬', 'name': 'Сингапурский доллар', 'price': '349,80 ₸', 'change': '+0,90 ₸', 'isUp': true},
  'THB': {'flag': '🇹🇭', 'name': 'Тайский бат', 'price': '13,40 ₸', 'change': '+0,08 ₸', 'isUp': true},
  'TRY': {'flag': '🇹🇷', 'name': 'Турецкая лира', 'price': '14,20 ₸', 'change': '-0,30 ₸', 'isUp': false},
  'UAH': {'flag': '🇺🇦', 'name': 'Украинская гривна', 'price': '11,80 ₸', 'change': '+0,05 ₸', 'isUp': true},
  'UZS': {'flag': '🇺🇿', 'name': 'Узбекский сум', 'price': '0,037 ₸', 'change': '+0,001 ₸', 'isUp': true},
  'ZAR': {'flag': '🇿🇦', 'name': 'Южноафриканский рэнд', 'price': '25,90 ₸', 'change': '+0,40 ₸', 'isUp': true},
  'ARS': {'flag': '🇦🇷', 'name': 'Аргентинское песо', 'price': '0,50 ₸', 'change': '+0,01 ₸', 'isUp': true},
  'EGP': {'flag': '🇪🇬', 'name': 'Египетский фунт', 'price': '9,80 ₸', 'change': '+0,05 ₸', 'isUp': true},
  'ILS': {'flag': '🇮🇱', 'name': 'Израильский шекель', 'price': '132,40 ₸', 'change': '+0,60 ₸', 'isUp': true},
  'IDR': {'flag': '🇮🇩', 'name': 'Индонезийская рупия', 'price': '0,031 ₸', 'change': '+0,001 ₸', 'isUp': true},
  'ISK': {'flag': '🇮🇸', 'name': 'Исландская крона', 'price': '3,45 ₸', 'change': '+0,02 ₸', 'isUp': true},
  'COP': {'flag': '🇨🇴', 'name': 'Колумбийское песо', 'price': '0,12 ₸', 'change': '+0,01 ₸', 'isUp': true},
  'KWD': {'flag': '🇰🇼', 'name': 'Кувейтский динар', 'price': '1620,50 ₸', 'change': '+5,20 ₸', 'isUp': true},
  'MYR': {'flag': '🇲🇾', 'name': 'Малайзийский ринггит', 'price': '108,30 ₸', 'change': '+0,40 ₸', 'isUp': true},
  'MAD': {'flag': '🇲🇦', 'name': 'Марокканский дирхам', 'price': '48,70 ₸', 'change': '+0,20 ₸', 'isUp': true},
  'NGN': {'flag': '🇳🇬', 'name': 'Нигерийская найра', 'price': '0,32 ₸', 'change': '+0,01 ₸', 'isUp': true},
  'PKR': {'flag': '🇵🇰', 'name': 'Пакистанская рупия', 'price': '1,75 ₸', 'change': '+0,02 ₸', 'isUp': true},
  'PEN': {'flag': '🇵🇪', 'name': 'Перуанский соль', 'price': '131,20 ₸', 'change': '+0,50 ₸', 'isUp': true},
  'RON': {'flag': '🇷🇴', 'name': 'Румынский лей', 'price': '106,80 ₸', 'change': '+0,35 ₸', 'isUp': true},
  'SAR': {'flag': '🇸🇦', 'name': 'Саудовский риял', 'price': '133,20 ₸', 'change': '+0,45 ₸', 'isUp': true},
  'PHP': {'flag': '🇵🇭', 'name': 'Филиппинское песо', 'price': '8,65 ₸', 'change': '+0,10 ₸', 'isUp': true},
  'CZK': {'flag': '🇨🇿', 'name': 'Чешская крона', 'price': '21,40 ₸', 'change': '+0,15 ₸', 'isUp': true},
  'CLP': {'flag': '🇨🇱', 'name': 'Чилийское песо', 'price': '0,52 ₸', 'change': '+0,01 ₸', 'isUp': true},
  'LKR': {'flag': '🇱🇰', 'name': 'Шри-Ланкийская рупия', 'price': '1,54 ₸', 'change': '+0,02 ₸', 'isUp': true},
  'VND': {'flag': '🇻🇳', 'name': 'Вьетнамский донг', 'price': '0,020 ₸', 'change': '+0,001 ₸', 'isUp': true},
};

final Map<String, Map<String, dynamic>> worldCrypto = {
  'BTC': {'symbol': '₿', 'name': 'Bitcoin', 'price': '72897 \$', 'change': '+2,4%', 'isUp': true},
  'ETH': {'symbol': 'Ξ', 'name': 'Ethereum', 'price': '3245 \$', 'change': '+1,8%', 'isUp': true},
  'USDT': {'symbol': '₮', 'name': 'Tether', 'price': '1,00 \$', 'change': '0,0%', 'isUp': true},
  'BNB': {'symbol': 'B', 'name': 'Binance Coin', 'price': '412 \$', 'change': '+3,2%', 'isUp': true},
  'SOL': {'symbol': 'S', 'name': 'Solana', 'price': '145 \$', 'change': '+5,4%', 'isUp': true},
  'XRP': {'symbol': 'X', 'name': 'Ripple', 'price': '0,58 \$', 'change': '+1,2%', 'isUp': true},
  'ADA': {'symbol': 'A', 'name': 'Cardano', 'price': '0,62 \$', 'change': '+2,1%', 'isUp': true},
  'DOGE': {'symbol': 'Ð', 'name': 'Dogecoin', 'price': '0,15 \$', 'change': '+4,5%', 'isUp': true},
  'TRX': {'symbol': 'T', 'name': 'Tron', 'price': '0,11 \$', 'change': '+1,8%', 'isUp': true},
  'MATIC': {'symbol': 'M', 'name': 'Polygon', 'price': '0,89 \$', 'change': '+3,1%', 'isUp': true},
  'DOT': {'symbol': 'D', 'name': 'Polkadot', 'price': '7,32 \$', 'change': '+2,5%', 'isUp': true},
  'LTC': {'symbol': 'Ł', 'name': 'Litecoin', 'price': '94 \$', 'change': '+1,9%', 'isUp': true},
  'SHIB': {'symbol': 'S', 'name': 'Shiba Inu', 'price': '0,000024 \$', 'change': '+8,2%', 'isUp': true},
  'AVAX': {'symbol': 'A', 'name': 'Avalanche', 'price': '38 \$', 'change': '+4,1%', 'isUp': true},
  'UNI': {'symbol': 'U', 'name': 'Uniswap', 'price': '11 \$', 'change': '+2,8%', 'isUp': true},
  'LINK': {'symbol': 'L', 'name': 'Chainlink', 'price': '16 \$', 'change': '+3,5%', 'isUp': true},
  'XLM': {'symbol': 'X', 'name': 'Stellar', 'price': '0,12 \$', 'change': '+1,5%', 'isUp': true},
  'ATOM': {'symbol': 'A', 'name': 'Cosmos', 'price': '9,45 \$', 'change': '+2,3%', 'isUp': true},
  'XMR': {'symbol': 'M', 'name': 'Monero', 'price': '168 \$', 'change': '+1,7%', 'isUp': true},
  'ETC': {'symbol': 'E', 'name': 'Ethereum Classic', 'price': '27 \$', 'change': '+2,9%', 'isUp': true},
  'BCH': {'symbol': 'B', 'name': 'Bitcoin Cash', 'price': '485 \$', 'change': '+3,4%', 'isUp': true},
  'NEAR': {'symbol': 'N', 'name': 'NEAR Protocol', 'price': '5,82 \$', 'change': '+4,2%', 'isUp': true},
  'APT': {'symbol': 'A', 'name': 'Aptos', 'price': '12 \$', 'change': '+5,1%', 'isUp': true},
  'FIL': {'symbol': 'F', 'name': 'Filecoin', 'price': '6,78 \$', 'change': '+2,6%', 'isUp': true},
  'VET': {'symbol': 'V', 'name': 'VeChain', 'price': '0,045 \$', 'change': '+3,8%', 'isUp': true},
  'ALGO': {'symbol': 'A', 'name': 'Algorand', 'price': '0,32 \$', 'change': '+2,1%', 'isUp': true},
  'ICP': {'symbol': 'I', 'name': 'Internet Computer', 'price': '13 \$', 'change': '+4,5%', 'isUp': true},
  'HBAR': {'symbol': 'H', 'name': 'Hedera', 'price': '0,089 \$', 'change': '+3,2%', 'isUp': true},
  'QNT': {'symbol': 'Q', 'name': 'Quant', 'price': '124 \$', 'change': '+2,7%', 'isUp': true},
  'ARB': {'symbol': 'A', 'name': 'Arbitrum', 'price': '1,85 \$', 'change': '+5,3%', 'isUp': true},
  'OP': {'symbol': 'O', 'name': 'Optimism', 'price': '3,42 \$', 'change': '+4,8%', 'isUp': true},
  'IMX': {'symbol': 'I', 'name': 'Immutable X', 'price': '2,67 \$', 'change': '+3,9%', 'isUp': true},
  'AAVE': {'symbol': 'A', 'name': 'Aave', 'price': '168 \$', 'change': '+2,4%', 'isUp': true},
  'MKR': {'symbol': 'M', 'name': 'Maker', 'price': '2845 \$', 'change': '+1,8%', 'isUp': true},
  'GRT': {'symbol': 'G', 'name': 'The Graph', 'price': '0,28 \$', 'change': '+3,5%', 'isUp': true},
  'SNX': {'symbol': 'S', 'name': 'Synthetix', 'price': '3,89 \$', 'change': '+4,1%', 'isUp': true},
  'SAND': {'symbol': 'S', 'name': 'The Sandbox', 'price': '0,68 \$', 'change': '+5,2%', 'isUp': true},
  'MANA': {'symbol': 'M', 'name': 'Decentraland', 'price': '0,72 \$', 'change': '+4,7%', 'isUp': true},
  'AXS': {'symbol': 'A', 'name': 'Axie Infinity', 'price': '9,34 \$', 'change': '+3,6%', 'isUp': true},
  'THETA': {'symbol': 'Θ', 'name': 'Theta Network', 'price': '2,15 \$', 'change': '+2,9%', 'isUp': true},
  'FTM': {'symbol': 'F', 'name': 'Fantom', 'price': '0,58 \$', 'change': '+4,3%', 'isUp': true},
  'EOS': {'symbol': 'E', 'name': 'EOS', 'price': '1,12 \$', 'change': '+2,1%', 'isUp': true},
  'XTZ': {'symbol': 'X', 'name': 'Tezos', 'price': '1,45 \$', 'change': '+3,4%', 'isUp': true},
  'FLOW': {'symbol': 'F', 'name': 'Flow', 'price': '1,28 \$', 'change': '+4,6%', 'isUp': true},
  'EGLD': {'symbol': 'E', 'name': 'MultiversX', 'price': '58 \$', 'change': '+3,8%', 'isUp': true},
  'XEC': {'symbol': 'X', 'name': 'eCash', 'price': '0,000045 \$', 'change': '+5,1%', 'isUp': true},
  'KLAY': {'symbol': 'K', 'name': 'Klaytn', 'price': '0,24 \$', 'change': '+2,7%', 'isUp': true},
  'CHZ': {'symbol': 'C', 'name': 'Chiliz', 'price': '0,13 \$', 'change': '+4,2%', 'isUp': true},
  'ZEC': {'symbol': 'Z', 'name': 'Zcash', 'price': '42 \$', 'change': '+2,5%', 'isUp': true},
  'DASH': {'symbol': 'D', 'name': 'Dash', 'price': '38 \$', 'change': '+3,1%', 'isUp': true},
  'NEO': {'symbol': 'N', 'name': 'NEO', 'price': '15 \$', 'change': '+2,8%', 'isUp': true},
  'IOTA': {'symbol': 'I', 'name': 'IOTA', 'price': '0,32 \$', 'change': '+3,9%', 'isUp': true},
  'ENJ': {'symbol': 'E', 'name': 'Enjin Coin', 'price': '0,45 \$', 'change': '+4,5%', 'isUp': true},
  'BAT': {'symbol': 'B', 'name': 'Basic Attention', 'price': '0,28 \$', 'change': '+2,3%', 'isUp': true},
  'ZIL': {'symbol': 'Z', 'name': 'Zilliqa', 'price': '0,034 \$', 'change': '+3,7%', 'isUp': true},
  'COMP': {'symbol': 'C', 'name': 'Compound', 'price': '68 \$', 'change': '+2,9%', 'isUp': true},
  'YFI': {'symbol': 'Y', 'name': 'yearn.finance', 'price': '9850 \$', 'change': '+1,6%', 'isUp': true},
  'CRV': {'symbol': 'C', 'name': 'Curve DAO', 'price': '0,89 \$', 'change': '+3,4%', 'isUp': true},
  'SUSHI': {'symbol': 'S', 'name': 'SushiSwap', 'price': '1,45 \$', 'change': '+4,1%', 'isUp': true},
  '1INCH': {'symbol': '1', 'name': '1inch', 'price': '0,52 \$', 'change': '+3,8%', 'isUp': true},
  'LRC': {'symbol': 'L', 'name': 'Loopring', 'price': '0,38 \$', 'change': '+4,6%', 'isUp': true},
  'GALA': {'symbol': 'G', 'name': 'Gala', 'price': '0,045 \$', 'change': '+5,2%', 'isUp': true},
  'ROSE': {'symbol': 'R', 'name': 'Oasis Network', 'price': '0,12 \$', 'change': '+3,5%', 'isUp': true},
  'ONE': {'symbol': 'O', 'name': 'Harmony', 'price': '0,023 \$', 'change': '+4,3%', 'isUp': true},
  'CELO': {'symbol': 'C', 'name': 'Celo', 'price': '0,89 \$', 'change': '+2,7%', 'isUp': true},
  'KSM': {'symbol': 'K', 'name': 'Kusama', 'price': '42 \$', 'change': '+3,2%', 'isUp': true},
  'WAVES': {'symbol': 'W', 'name': 'Waves', 'price': '2,85 \$', 'change': '+2,9%', 'isUp': true},
  'ZRX': {'symbol': 'Z', 'name': '0x', 'price': '0,56 \$', 'change': '+3,6%', 'isUp': true},
  'ICX': {'symbol': 'I', 'name': 'ICON', 'price': '0,34 \$', 'change': '+4,1%', 'isUp': true},
  'ONT': {'symbol': 'O', 'name': 'Ontology', 'price': '0,28 \$', 'change': '+2,8%', 'isUp': true},
  'QTUM': {'symbol': 'Q', 'name': 'Qtum', 'price': '3,45 \$', 'change': '+3,4%', 'isUp': true},
  'RVN': {'symbol': 'R', 'name': 'Ravencoin', 'price': '0,034 \$', 'change': '+4,7%', 'isUp': true},
  'SC': {'symbol': 'S', 'name': 'Siacoin', 'price': '0,0068 \$', 'change': '+3,9%', 'isUp': true},
  'DGB': {'symbol': 'D', 'name': 'DigiByte', 'price': '0,012 \$', 'change': '+2,5%', 'isUp': true},
  'HOT': {'symbol': 'H', 'name': 'Holo', 'price': '0,0034 \$', 'change': '+5,1%', 'isUp': true},
  'STX': {'symbol': 'S', 'name': 'Stacks', 'price': '2,15 \$', 'change': '+4,2%', 'isUp': true},
  'ANKR': {'symbol': 'A', 'name': 'Ankr', 'price': '0,045 \$', 'change': '+3,7%', 'isUp': true},
  'SKL': {'symbol': 'S', 'name': 'SKALE', 'price': '0,078 \$', 'change': '+4,5%', 'isUp': true},
  'STORJ': {'symbol': 'S', 'name': 'Storj', 'price': '0,68 \$', 'change': '+3,3%', 'isUp': true},
  'OCEAN': {'symbol': 'O', 'name': 'Ocean Protocol', 'price': '0,89 \$', 'change': '+4,8%', 'isUp': true},
  'BAND': {'symbol': 'B', 'name': 'Band Protocol', 'price': '1,85 \$', 'change': '+2,6%', 'isUp': true},
  'REN': {'symbol': 'R', 'name': 'Ren', 'price': '0,12 \$', 'change': '+3,9%', 'isUp': true},
  'NKN': {'symbol': 'N', 'name': 'NKN', 'price': '0,15 \$', 'change': '+4,1%', 'isUp': true},
  'FET': {'symbol': 'F', 'name': 'Fetch.ai', 'price': '0,78 \$', 'change': '+3,5%', 'isUp': true},
  'INJ': {'symbol': 'I', 'name': 'Injective', 'price': '28 \$', 'change': '+4,9%', 'isUp': true},
  'RUNE': {'symbol': 'R', 'name': 'THORChain', 'price': '5,67 \$', 'change': '+3,2%', 'isUp': true},
  'KAVA': {'symbol': 'K', 'name': 'Kava', 'price': '1,23 \$', 'change': '+2,8%', 'isUp': true},
  'LUNA': {'symbol': 'L', 'name': 'Terra Luna', 'price': '0,00012 \$', 'change': '+8,5%', 'isUp': true},
  'PEPE': {'symbol': 'P', 'name': 'Pepe', 'price': '0,0000089 \$', 'change': '+12,3%', 'isUp': true},
  'FLOKI': {'symbol': 'F', 'name': 'Floki Inu', 'price': '0,000045 \$', 'change': '+9,1%', 'isUp': true},
  'BONK': {'symbol': 'B', 'name': 'Bonk', 'price': '0,000023 \$', 'change': '+15,6%', 'isUp': true},
  'WLD': {'symbol': 'W', 'name': 'Worldcoin', 'price': '4,85 \$', 'change': '+6,3%', 'isUp': true},
};
